### ISSUE TITLE
Will there be another release soon and will it include the pre-commit hook for CFF validation?

### ISSUE THREAD

**Issue by apirogov** [citation-file-format/cffconvert#284]
Currently I use the main branch latest commit:

```yaml
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: "44e8fc9"
    hooks:
      - id: validate-cff
```

Would be great to see the hook in a tagged version, which I could put instead of the `rev`.
